In [ ]:
import pandas as pd

In [ ]:
from pandas import Series

In [ ]:
sells = [120, 150, 180 ,210]

In [ ]:
marks = Series([72, 81, 69, 90])
marks

0    72
1    81
2    69
3    90
dtype: int64

In [ ]:
marks.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
temp = Series([28, 31, 30 ,29],index=['Mon', 'Tue', 'Wed', 'Thu'])
temp

Mon    28
Tue    31
Wed    30
Thu    29
dtype: int64

In [ ]:
population = Series([35, 42, 31], index=['Delhi','Mumbai','Jaipur'])

In [ ]:
population['Jaipur']

np.int64(31)

In [ ]:
score = Series([35, 68, 44, 79, 52])

In [ ]:
score[score>50]

1    68
3    79
4    52
dtype: int64

In [ ]:
subjects = Series([76, 83, 91], index=['Physics','Chemistry','Maths'])
'Chemistry' in subjects

True

In [ ]:
newdict = subjects.to_dict()
type(newdict)
newdict

{'Physics': 76, 'Chemistry': 83, 'Maths': 91}

In [ ]:
prices = {'Pen': 10,'Notebook': 55,'Bag': 700}

In [ ]:
newseries = Series(prices)
newseries

Pen          10
Notebook     55
Bag         700
dtype: int64

Answer: 10

The dictionary's keys become the Series index, and their order is preserved. The corresponding dictionary values become the values of the Series.

In [ ]:
data = {'A': 10,'B': 20,'C': 30}
s = Series(data, index=['A','B','C','D'])
s
#it shows the Value of index is NaN.

A    10.0
B    20.0
C    30.0
D     NaN
dtype: float64

In [ ]:
s.isnull()['D']
#isnull(s['D'])

np.True_

In [ ]:
s.notnull()

A     True
B     True
C     True
D    False
dtype: bool

In [ ]:
Montly_sales = Series([28, 31, 30 ,29])
Montly_sales

0    28
1    31
2    30
3    29
dtype: int64

In [ ]:
Montly_sales.name = "Month"
Montly_sales

0    28
1    31
2    30
3    29
Name: Month, dtype: int64

In [ ]:
s = Series([18, 45, 27, 61], index=['P','Q','R','S'])
s[s>30]
#Predicted Output is (45,61)

Q    45
S    61
dtype: int64

In [ ]:
s = Series([500, 600, 700], index=["East","West","North"])
(500 in s)
"North" in s
### It will give True because "North" in s loaded in last. But 500 in s gives False because in operator checks only keys.

True

In [ ]:
city_data = {"Delhi":80,"Pune":65,"Kochi":70}
s3 = Series(city_data,index=["Delhi","Pune","Kochi","Mumbai"])
s3

Delhi     80.0
Pune      65.0
Kochi     70.0
Mumbai     NaN
dtype: float64

In [ ]:
s = Series({'W': 5,'X': 10,'Y': 15}, index=['W','X','Y','Z'])
print(pd.isnull(s))

W    False
X    False
Y    False
Z     True
dtype: bool

In [ ]:
s = Series({'W': 5,'X': 10,'Y': 15}, index=['W','X','Y','Z'])
print(pd.notnull(s))

W     True
X     True
Y     True
Z    False
dtype: bool

In [ ]:
s4 = Series([10,20,30], index=['A','B','C'])
s5 = Series([1,2,3], index=['C','A','B'])
s4+s5

A    12
B    23
C    31
dtype: int64

In [ ]:
s9= Series({'A': 12,'B': 18})
s8 = Series({'B': 5,'C': 9})
s9+s8

A     NaN
B    23.0
C     NaN
dtype: float64

In [ ]:
stock = Series([20,40,18],index = ['item1','item2','item3'])
new = stock.to_dict()
new

{'item1': 20, 'item2': 40, 'item3': 18}

In [ ]:
marks = {'Math':88,'Science':74,'English':69,'History':81}
ser = Series(marks)
ser[ser>70]

Math       88
Science    74
History    81
dtype: int64

In [ ]:
Rev = Series([299,746,373],index = ['Education','Grocery','Others'])
Rev.name = 'Revenue'
Rev.index.name = 'Branch'
Rev

Branch
Education    299
Grocery      746
Others       373
Name: Revenue, dtype: int64

Answer: 26

'Jan' = NaN

'Feb' = 75.0

'Mar' = *85.0*

'Apr' = NaN

Answer:27

(a) -> Yellow have NaN value

(b) -> False for(Red,Blue,Green) and True for **Yellow**

(c) -> Because, Yellow present in index labels but not in given Dictionary so Pandas consider that is a explicit index

(d) -> **Red,Blue,Green** retains their Numeric values because it is initialized in Dict..

**Answer: 28**

YES, s ans s2 both prints the same data because s converted to d and again d converted to s2.

In [ ]:
buss = Series([50000,63000,83000,53700],index=['Fan','A.C','T.V','Lights'])
buss.name = "Sales"
buss.index.name = "Products"
buss

Products
Fan       50000
A.C       63000
T.V       83000
Lights    53700
Name: Sales, dtype: int64

**Answer:30**

(a) -> 'A','B','C','D'

(b) -> 'D' = NaN

(c) -> False
      True
      True
      False

(d) -> True